### PR TITLE
Only create path for motion magic once

### PR DESCRIPTION
**Pull request by eandr127**
## Summary of Changes
Only generate motion magic profile to run once

## Testing Performed
**Environment**:  Plyboy

### CODE REVIEW

**Comment by KyleRAnderson** [comment]
@eandr127 do you want to merge this?

**Comment by eandr127** [comment]
I'm just waiting for @carmen1234 to review since she's the one that did motion magic.

**Comment by eandr127** [comment]
I took a look at the Talon manual and the example code. It seems like you're actually supposed to set the motion magic position periodically, so this might need to be reverted.

**Comment by KyleRAnderson** [comment]
When I did that for the lift it didn't work @eandr127.

**Pull request merged**
